// convex/sdk/registry.ts
import { FULL_PROMPTS } from './prompts';

export interface ToolDefinition {
  id: string;
  kind: 'agent' | 'tool'; // agent = iterative loop, tool = single shot
  systemPrompt: string;
  description: string;
  model: string;
  temperature?: number;
  allowedTools?: string[];
  schemaName: string;
}

export const REGISTRY: Record<string, ToolDefinition> = {
  // Orchestrator
  orchestrator: {
    id: 'orchestrator',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.ORCHESTRATOR_SYSTEM,
    description: 'Top-level orchestrator that delegates to tools/agents',
    model: 'gpt-5.2',
    allowedTools: [
      'context.get',
      'knowledge.summarize_or_update',
      'web_search',
      'changeset.compile',
      'changeset.review',
      'changeset.apply',
      'clarify.next_questions',
      'chat.free',
      'think.deep',
      'pricing.resolve_lines',
      'procurement.shopping_plan',
      'finance.ingest_receipt',
      'audit.project',
      'qa.print_files',
      'maint.sync_and_repair',
      'audit.fix_plan',
      'intake.parse_brief',
      'plan.elements',
      'plan.tasks',
      'plan.execution_phases',
      'cost.build_budget',
      'quote.generate',
      'runbook.installation',
      'ops.daily_plan',
      'finalize.build_structured_package',
      'admin.set_labor_rates',
      'admin.confirm_measurements',
    ],
    schemaName: 'orchestrator.response',
  },
  // Option A: Agents (Iterative)
  'clarify.next_questions': {
    id: 'clarify.next_questions',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.CLARIFY_SYSTEM,
    description: 'Iterative clarification loop to unlock next stage',
    model: 'gpt-5-mini',
    allowedTools: ['context.get', 'knowledge.summarize_or_update'],
    schemaName: 'clarify.next_questions',
  },
  'chat.free': {
    id: 'chat.free',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.FREE_CHAT_SYSTEM,
    description: 'Free chat for brain dump and fact extraction',
    model: 'gpt-5.2',
    allowedTools: ['context.get', 'knowledge.summarize_or_update', 'think.deep', 'web_search'],
    schemaName: 'chat.free',
  },
  'think.deep': {
    id: 'think.deep',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.THINK_DEEP_SYSTEM,
    description: 'Deep research and strategic analysis agent',
    model: 'gpt-5.2',
    allowedTools: ['context.get', 'knowledge.summarize_or_update', 'web_search'],
    schemaName: 'think.deep',
  },
  'pricing.resolve_lines': {
    id: 'pricing.resolve_lines',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.PRICING_SYSTEM,
    description: 'Resolve missing/uncertain prices for accounting lines',
    model: 'gpt-5-mini',
    allowedTools: ['context.get', 'knowledge.summarize_or_update', 'web_search'],
    schemaName: 'pricing.resolve_lines',
  },
  'procurement.shopping_plan': {
    id: 'procurement.shopping_plan',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.PROCUREMENT_SYSTEM,
    description: 'Create procurement plan with vendors and timing',
    model: 'gpt-5-mini',
    allowedTools: ['context.get', 'knowledge.summarize_or_update', 'web_search'],
    schemaName: 'procurement.shopping_plan',
  },
  'finance.ingest_receipt': {
    id: 'finance.ingest_receipt',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.RECEIPT_SYSTEM,
    description: 'Parse receipts and map to material lines',
    model: 'gpt-5-mini',
    allowedTools: ['context.get', 'knowledge.summarize_or_update'],
    schemaName: 'finance.ingest_receipt',
  },
  'audit.project': {
    id: 'audit.project',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.AUDIT_SYSTEM,
    description: 'Criticize plan for completeness and safety',
    model: 'gpt-5.2',
    allowedTools: ['context.get'],
    schemaName: 'audit.project',
  },
  'qa.print_files': {
    id: 'qa.print_files',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.PRINT_QA_SYSTEM,
    description: 'QA print deliverables and metadata',
    model: 'gpt-5-mini',
    allowedTools: ['context.get', 'knowledge.summarize_or_update'],
    schemaName: 'qa.print_files',
  },
  'maint.sync_and_repair': {
    id: 'maint.sync_and_repair',
    kind: 'agent',
    systemPrompt: FULL_PROMPTS.MAINTENANCE_SYSTEM,
    description: 'Repair data integrity issues iteratively',
    model: 'gpt-5.2',
    allowedTools: ['context.get', 'audit.project', 'knowledge.summarize_or_update'],
    schemaName: 'maint.sync_and_repair',
  },
  'audit.fix_plan': {
    id: 'audit.fix_plan',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.AUDIT_FIX_SYSTEM,
    description: 'Generate fix intents from audit findings',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'audit.fix_plan',
  },

  // Option B: Tools (Single Shot)
  'intake.parse_brief': {
    id: 'intake.parse_brief',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.INTAKE_BRIEF_SYSTEM,
    description: 'Parse user input into structured project brief',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'intake.parse_brief',
  },
  'draft.plan_and_questions': {
    id: 'draft.plan_and_questions',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.DRAFT_PLAN_AND_QUESTIONS_SYSTEM,
    description: 'Single-pass draft of PlanDoc + seeded question backlog',
    model: 'gpt-5.2',
    allowedTools: [],
    schemaName: 'draft.plan_and_questions',
  },
  'plan.elements': {
    id: 'plan.elements',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.PLAN_ELEMENTS_SYSTEM,
    description: 'Generate elements plan',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'plan.elements',
  },
  'plan.tasks': {
    id: 'plan.tasks',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.PLAN_TASKS_SYSTEM,
    description: 'Generate tasks linked to elements',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'plan.tasks',
  },
  'plan.execution_phases': {
    id: 'plan.execution_phases',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.PLAN_PHASES_SYSTEM,
    description: 'Generate execution phases and gates',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'plan.execution_phases',
  },
  'cost.build_budget': {
    id: 'cost.build_budget',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.COST_BUDGET_SYSTEM,
    description: 'Generate budget structure (BOM + Labor)',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'cost.build_budget',
  },
  'quote.generate': {
    id: 'quote.generate',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.QUOTE_GENERATE_SYSTEM,
    description: 'Generate client quote draft',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'quote.generate',
  },
  'runbook.installation': {
    id: 'runbook.installation',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.RUNBOOK_INSTALL_SYSTEM,
    description: 'Generate install-day runbook',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'runbook.installation',
  },
  'ops.daily_plan': {
    id: 'ops.daily_plan',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.OPS_DAILY_SYSTEM,
    description: 'Generate daily execution plan',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'ops.daily_plan',
  },
  'changeset.compile': {
    id: 'changeset.compile',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.CHANGESET_COMPILE_SYSTEM,
    description: 'Compile intents into valid ChangeSet',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'changeset.compile',
  },
  'changeset.review': {
    id: 'changeset.review',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.CHANGESET_REVIEW_SYSTEM,
    description: 'Review and validate ChangeSet',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'changeset.review',
  },
  'finalize.build_structured_package': {
    id: 'finalize.build_structured_package',
    kind: 'tool',
    systemPrompt: 'Return JSON only. The package is built deterministically by tool implementation.',
    description: 'Build final structured package from plan + qa state',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'finalize.build_structured_package',
  },
  'admin.set_labor_rates': {
    id: 'admin.set_labor_rates',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.ADMIN_RATES_SYSTEM,
    description: 'Validate and normalize labor rates',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'admin.set_labor_rates',
  },
  'admin.confirm_measurements': {
    id: 'admin.confirm_measurements',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.ADMIN_MEASUREMENTS_SYSTEM,
    description: 'Validate confirmed measurements',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'admin.confirm_measurements',
  },
  'knowledge.summarize_or_update': {
    id: 'knowledge.summarize_or_update',
    kind: 'tool',
    systemPrompt: FULL_PROMPTS.KNOWLEDGE_UPDATE_SYSTEM,
    description: 'Update working knowledge doc',
    model: 'gpt-5-mini',
    allowedTools: [],
    schemaName: 'knowledge.summarize_or_update',
  },
};

